config/routes.rb
Rails.application.routes.draw do
  resources :fights

  resources :fighters

end

app/models/fight.rb
class Fight < ActiveRecord::Base
  belongs_to :fighter1, foreign_key: "fighter1_id", class_name: "Fighter"
  belongs_to :fighter2, foreign_key: "fighter2_id", class_name: "Fighter"

  def fighter1_actual_return
    actual_return(fighter1_result, fighter1_betting_line)
  end

  def fighter2_actual_return
    actual_return(fighter2_result, fighter2_betting_line)
  end

  def actual_return(fight_result, betting_line)
    if fight_result == 'win'
      if betting_line.to_i < 0
        win_return = 100 / betting_line.to_f.abs
      else
        win_return = betting_line.to_f / 100
      end
    else
      -1
    end
  end
end

app/models/fighter.rb
class Fighter < ActiveRecord::Base
  has_many :fights

  attr_accessor :elo_player
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  before_action :set_fighter, only: [:show, :edit, :update, :destroy]

  # GET /fighters
  # GET /fighters.json
  def index
    @fighters = Fighter.all
  end

  # GET /fighters/1
  # GET /fighters/1.json
  def show
  end

  # GET /fighters/new
  def new
    @fighter = Fighter.new
  end

  # GET /fighters/1/edit
  def edit
  end

  # POST /fighters
  # POST /fighters.json
  def create
    @fighter = Fighter.new(fighter_params)

    respond_to do |format|
      if @fighter.save
        format.html { redirect_to @fighter, notice: 'Fighter was successfully created.' }
        format.json { render :show, status: :created, location: @fighter }
      else
        format.html { render :new }
        format.json { render json: @fighter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fighters/1
  # PATCH/PUT /fighters/1.json
  def update
    respond_to do |format|
      if @fighter.update(fighter_params)
        format.html { redirect_to @fighter, notice: 'Fighter was successfully updated.' }
        format.json { render :show, status: :ok, location: @fighter }
      else
        format.html { render :edit }
        format.json { render json: @fighter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fighters/1
  # DELETE /fighters/1.json
  def destroy
    @fighter.destroy
    respond_to do |format|
      format.html { redirect_to fighters_url, notice: 'Fighter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fighter
      @fighter = Fighter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fighter_params
      params.require(:fighter).permit(:name, :born_on, :nationality, :url)
    end
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  before_action :set_fight, only: [:show, :edit, :update, :destroy]

  # GET /fights
  # GET /fights.json
  def index
    sort_column = params[:sort] || "fought_on"
    sort_direction = params[:sort_dir] || "desc"
    @fights = Fight.all.includes(:fighter1).includes(:fighter2).order("#{sort_column} #{sort_direction}")
  end

  # GET /fights/1
  # GET /fights/1.json
  def show
  end

  # GET /fights/new
  def new
    @fight = Fight.new
  end

  # GET /fights/1/edit
  def edit
  end

  # POST /fights
  # POST /fights.json
  def create
    @fight = Fight.new(fight_params)

    respond_to do |format|
      if @fight.save
        format.html { redirect_to @fight, notice: 'Fight was successfully created.' }
        format.json { render :show, status: :created, location: @fight }
      else
        format.html { render :new }
        format.json { render json: @fight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fights/1
  # PATCH/PUT /fights/1.json
  def update
    respond_to do |format|
      if @fight.update(fight_params)
        format.html { redirect_to @fight, notice: 'Fight was successfully updated.' }
        format.json { render :show, status: :ok, location: @fight }
      else
        format.html { render :edit }
        format.json { render json: @fight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fights/1
  # DELETE /fights/1.json
  def destroy
    @fight.destroy
    respond_to do |format|
      format.html { redirect_to fights_url, notice: 'Fight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fight
      @fight = Fight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fight_params
      params.require(:fight).permit(:event_name, :event_url, :fighter1_id, :fighter1_result, :fighter1_result_elo, :fighter2_id, :fighter2_result, :fighter2_result_elo, :fought_on, :location, :referee, :result_method, :result_round, :result_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fighters_helper.rb
module FightersHelper
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/views/fighters/_form.html.erb
<%= form_for(@fighter) do |f| %>
  <% if @fighter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fighter.errors.count, "error") %> prohibited this fighter from being saved:</h2>

      <ul>
      <% @fighter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :born_on %><br>
    <%= f.date_select :born_on %>
  </div>
  <div class="field">
    <%= f.label :nationality %><br>
    <%= f.text_field :nationality %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fighters/edit.html.erb
<h1>Editing fighter</h1>

<%= render 'form' %>

<%= link_to 'Show', @fighter %> |
<%= link_to 'Back', fighters_path %>

app/views/fighters/index.html.erb
<h1>Listing fighters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Born on</th>
      <th>Nationality</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fighters.each do |fighter| %>
      <tr>
        <td><%= fighter.name %></td>
        <td><%= fighter.born_on %></td>
        <td><%= fighter.nationality %></td>
        <td><%= fighter.url %></td>
        <td><%= link_to 'Show', fighter %></td>
        <td><%= link_to 'Edit', edit_fighter_path(fighter) %></td>
        <td><%= link_to 'Destroy', fighter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fighter', new_fighter_path %>

app/views/fighters/new.html.erb
<h1>New fighter</h1>

<%= render 'form' %>

<%= link_to 'Back', fighters_path %>

app/views/fighters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fighter.name %>
</p>

<p>
  <strong>Born on:</strong>
  <%= @fighter.born_on %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @fighter.nationality %>
</p>

<p>
  <strong>Url:</strong>
  <%= @fighter.url %>
</p>

<%= link_to 'Edit', edit_fighter_path(@fighter) %> |
<%= link_to 'Back', fighters_path %>

app/views/fights/_form.html.erb
<%= form_for(@fight) do |f| %>
  <% if @fight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fight.errors.count, "error") %> prohibited this fight from being saved:</h2>

      <ul>
      <% @fight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_name %><br>
    <%= f.text_field :event_name %>
  </div>
  <div class="field">
    <%= f.label :event_url %><br>
    <%= f.text_field :event_url %>
  </div>
  <div class="field">
    <%= f.label :fighter1_id %><br>
    <%= f.number_field :fighter1_id %>
  </div>
  <div class="field">
    <%= f.label :fighter1_result %><br>
    <%= f.text_field :fighter1_result %>
  </div>
  <div class="field">
    <%= f.label :fighter1_result_elo %><br>
    <%= f.number_field :fighter1_result_elo %>
  </div>
  <div class="field">
    <%= f.label :fighter2_id %><br>
    <%= f.number_field :fighter2_id %>
  </div>
  <div class="field">
    <%= f.label :fighter2_result %><br>
    <%= f.text_field :fighter2_result %>
  </div>
  <div class="field">
    <%= f.label :fighter2_result_elo %><br>
    <%= f.number_field :fighter2_result_elo %>
  </div>
  <div class="field">
    <%= f.label :fought_on %><br>
    <%= f.date_select :fought_on %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :referee %><br>
    <%= f.text_field :referee %>
  </div>
  <div class="field">
    <%= f.label :result_method %><br>
    <%= f.text_field :result_method %>
  </div>
  <div class="field">
    <%= f.label :result_round %><br>
    <%= f.text_field :result_round %>
  </div>
  <div class="field">
    <%= f.label :result_time %><br>
    <%= f.text_field :result_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fights/edit.html.erb
<h1>Editing fight</h1>

<%= render 'form' %>

<%= link_to 'Show', @fight %> |
<%= link_to 'Back', fights_path %>

app/views/fights/index.html.erb
<h1>Listing fights</h1>

<table>
  <thead>
    <tr>
      <th>Event name</th>
      <th>Event url</th>
      <th>Fighter1</th>
      <th>Fighter1 result</th>
      <th>Fighter1 result elo</th>
      <th>Fighter1 result elo count</th>
      <th>Fighter1 predicted chance to win</th>
      <th>Fighter1 betting line</th>
      <th>Fighter1 expected return</th>
      <th>Fighter1 actual return</th>
      <th>Fighter2</th>
      <th>Fighter2 result</th>
      <th>Fighter2 result elo</th>
      <th>Fighter2 result elo count</th>
      <th>Fighter2 predicted chance to win</th>
      <th>Fighter2 betting line</th>
      <th>Fighter2 expected return</th>
      <th>Fighter2 actual return</th>
      <th>Fought on</th>
      <th>Location</th>
      <th>Referee</th>
      <th>Result method</th>
      <th>Result round</th>
      <th>Result time</th>
      <th>Betting url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fights.each do |fight| %>
      <tr>
        <td><%= fight.event_name %></td>
        <td><%= fight.event_url %></td>
        <td><%= fight.fighter1.name %></td>
        <td><%= fight.fighter1_result %></td>
        <td><%= fight.fighter1_result_elo %></td>
        <td><%= fight.fighter1_result_elo_count %></td>
        <td><%= (fight.fighter1_predicted_chance_to_win * 100).round(1) %></td>
        <td><%= fight.fighter1_betting_line %></td>
        <td><%= fight.fighter1_betting_return.try(:round, 1) %></td>
        <td><%= fight.fighter1_actual_return.try(:round, 1) %></td>
        <td><%= fight.fighter2.name %></td>
        <td><%= fight.fighter2_result %></td>
        <td><%= fight.fighter2_result_elo %></td>
        <td><%= fight.fighter2_result_elo_count %></td>
        <td><%= (fight.fighter2_predicted_chance_to_win * 100).round(1) %></td>
        <td><%= fight.fighter2_betting_line %></td>
        <td><%= fight.fighter2_betting_return.try(:round, 1) %></td>
        <td><%= fight.fighter2_actual_return.try(:round, 1) %></td>
        <td><%= fight.fought_on %></td>
        <td><%= fight.location %></td>
        <td><%= fight.referee %></td>
        <td><%= fight.result_method %></td>
        <td><%= fight.result_round %></td>
        <td><%= fight.result_time %></td>
        <td><%= fight.betting_url %></td>
        <td><%= link_to 'Show', fight %></td>
        <td><%= link_to 'Edit', edit_fight_path(fight) %></td>
        <td><%= link_to 'Destroy', fight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fight', new_fight_path %>

app/views/fights/new.html.erb
<h1>New fight</h1>

<%= render 'form' %>

<%= link_to 'Back', fights_path %>

app/views/fights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event name:</strong>
  <%= @fight.event_name %>
</p>

<p>
  <strong>Event url:</strong>
  <%= @fight.event_url %>
</p>

<p>
  <strong>Fighter1:</strong>
  <%= @fight.fighter1_id %>
</p>

<p>
  <strong>Fighter1 result:</strong>
  <%= @fight.fighter1_result %>
</p>

<p>
  <strong>Fighter1 result elo:</strong>
  <%= @fight.fighter1_result_elo %>
</p>

<p>
  <strong>Fighter2:</strong>
  <%= @fight.fighter2_id %>
</p>

<p>
  <strong>Fighter2 result:</strong>
  <%= @fight.fighter2_result %>
</p>

<p>
  <strong>Fighter2 result elo:</strong>
  <%= @fight.fighter2_result_elo %>
</p>

<p>
  <strong>Fought on:</strong>
  <%= @fight.fought_on %>
</p>

<p>
  <strong>Location:</strong>
  <%= @fight.location %>
</p>

<p>
  <strong>Referee:</strong>
  <%= @fight.referee %>
</p>

<p>
  <strong>Result method:</strong>
  <%= @fight.result_method %>
</p>

<p>
  <strong>Result round:</strong>
  <%= @fight.result_round %>
</p>

<p>
  <strong>Result time:</strong>
  <%= @fight.result_time %>
</p>

<%= link_to 'Edit', edit_fight_path(@fight) %> |
<%= link_to 'Back', fights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UfcEdge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>